apiVersion: v1
kind: ConfigMap
metadata:
  name: node-order-scheduler-config
  namespace: scheduler-plugins
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
      - schedulerName: node-order-scheduler
        plugins:
          score:
            disabled:
              - name: NodeResourcesFit
            enabled:
              - name: node-order
          preFilter:
            enabled:
              - name: node-order
          filter:
            enabled:
              - name: node-order