apiVersion: v1
kind: Pod
metadata:
  name: test-cs001
  namespace: scheduler-plugins
  annotations:
    scheduler.alpha.kubernetes.io/node-order: node01,node02
  labels:
    app: test-cs
spec:
  containers:
    - name: test-cs
      image: nginx
  schedulerName: node-order-scheduler